export const LICENSES = [
    {
        id: "NO-LICENSE",
        name: "All Rights Reserved / No License",
        spdx: "no-license",
        url: "no-license",
        key: "no-license",
    },
    {
        id: "MIT",
        name: "MIT License",
        spdx: "MIT",
        key: "mit",
        url: "https://opensource.org/licenses/MIT",
    },
    {
        id: "APACHE-2.0",
        name: "Apache License 2.0",
        spdx: "Apache-2.0",
        key: "apache-2.0",
        url: "https://www.apache.org/licenses/LICENSE-2.0",
    },
    {
        id: "GPL-3.0-only",
        name: "GNU General Public License v3.0 only",
        spdx: "GPL-3.0-only",
        key: "gpl-3.0",
        url: "https://www.gnu.org/licenses/gpl-3.0",
    },
    {
        id: "GPL-2.0-only",
        name: "GNU General Public License v2.0 only",
        spdx: "GPL-2.0-only",
        key: "gpl-2.0",
        url: "https://www.gnu.org/licenses/old-licenses/gpl-2.0",
    },
    {
        id: "LGPL-2.1-only",
        name: "GNU Lesser General Public License v2.1 only",
        spdx: "LGPL-2.1-only",
        key: "lgpl-2.1",
        url: "https://www.gnu.org/licenses/old-licenses/lgpl-2.1",
    },
    {
        id: "AGPL-3.0-only",
        name: "GNU Affero General Public License v3.0 only",
        spdx: "AGPL-3.0-only",
        key: "agpl-3.0",
        url: "https://www.gnu.org/licenses/agpl-3.0",
    },
    {
        id: "BSD-2-Clause",
        name: 'BSD 2-Clause "Simplified" License',
        spdx: "BSD-2-Clause",
        key: "bsd-2-clause",
        url: "https://opensource.org/licenses/BSD-2-Clause",
    },
    {
        id: "BSD-3-Clause",
        name: 'BSD 3-Clause "New" or "Revised" License',
        spdx: "BSD-3-Clause",
        key: "bsd-3-clause",
        url: "https://opensource.org/licenses/BSD-3-Clause",
    },
    {
        id: "CC0-1.0",
        name: "Creative Commons Zero v1.0 Universal (Public Domain)",
        spdx: "CC0-1.0",
        key: "cc0-1.0",
        url: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    {
        id: "CC-BY-4.0",
        name: "Creative Commons Attribution 4.0 International",
        spdx: "CC-BY-4.0",
        key: null,
        url: "https://creativecommons.org/licenses/by/4.0/",
    },
    {
        id: "CC-BY-SA-4.0",
        name: "Creative Commons Attribution-ShareAlike 4.0 International",
        spdx: "CC-BY-SA-4.0",
        key: null,
        url: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    {
        id: "MPL-2.0",
        name: "Mozilla Public License 2.0",
        spdx: "MPL-2.0",
        key: "mpl-2.0",
        url: "https://www.mozilla.org/en-US/MPL/2.0/",
    },
    {
        id: "ISC",
        name: "ISC License",
        spdx: "ISC",
        key: null,
        url: "https://www.isc.org/licenses/",
    },
    {
        id: "ZLIB",
        name: "zlib License",
        spdx: "Zlib",
        key: null,
        url: "https://opensource.org/licenses/Zlib",
    },
    {
        id: "UNLICENSE",
        name: "The Unlicense",
        spdx: "Unlicense",
        key: "unlicense",
        url: "https://unlicense.org/",
    },
];